include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - always_use_package_imports

analyzer:
  exclude:
    - "**/__generated__/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
