name: aipictors

description: A new Flutter project.

publish_to: "none"

version: 1.1.2+18

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: 3.24.0-0.2.pre

dependencies:
  app_tracking_transparency: ^2.0.5
  app_links: ^6.1.3
  audioplayers: ^6.0.0
  built_collection: ^5.1.1
  cached_network_image: ^3.3.1
  connectivity_plus: 5.0.2 # Execution failed for task ':connectivity_plus:compileReleaseJavaWithJavac'.
  device_info_plus: ^10.1.0 # Execution failed for task ':device_info_plus:compileReleaseJavaWithJavac'
  dynamic_color: ^1.7.0
  ferry: ^0.15.0+1
  ferry_flutter: ^0.9.0
  ferry_hive_store: ^0.5.2
  firebase_analytics: ^11.1.0
  firebase_app_installations: ^0.3.0+2
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  # firebase_crashlytics: ^4.0.2
  firebase_in_app_messaging: ^0.8.0+4
  firebase_messaging: ^15.0.4
  firebase_remote_config: ^5.0.4
  flame: ^1.18.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_cache_manager: ^3.3.2
  flutter_hooks: ^0.20.5
  flutter_html: 3.0.0-beta.2
  # flutter_local_notifications: ^17.2.1 # flutter_local_notifications_linux:linux as the default plugin, but the package does not exist.
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.2
  go_router: ^14.2.0
  # google_sign_in: ^6.2.1
  gql_error_link: ^1.0.0+1
  gql_http_link: ^1.1.0
  gql_exec: ^1.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  i18n_extension: ^12.0.1
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  riverpod_annotation: ^2.3.5
  sentry_flutter: ^8.8.0-alpha.1
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.1
  # url_launcher: ^6.3.0 # error: type 'UIApplication' does not conform to protocol 'Launcher'
  webview_flutter: ^4.8.0
  like_button: ^2.0.5
  share_plus: ^9.0.0
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  ferry_generator: ^0.9.1-dev.2
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/snd_sine/
    - assets/snd_industrial/
    - assets/snd_piano/

flutter_launcher_icons:
  android: true
  ios: true
