name: aipictors

description: A new Flutter project.

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  built_collection: ^5.1.1
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  device_info_plus: ^9.0.2
  dynamic_color: ^1.6.5
  ferry: ^0.14.2+1
  ferry_flutter: ^0.8.1
  ferry_hive_store: ^0.5.1
  firebase_analytics: ^10.4.3
  firebase_app_installations: ^0.2.3+3
  firebase_auth: ^4.6.0
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_dynamic_links: ^5.3.3
  firebase_in_app_messaging: ^0.7.3+3
  firebase_messaging: ^14.6.4
  firebase_remote_config: ^4.2.3
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_cache_manager: ^3.3.0
  flutter_hooks: ^0.18.6
  flutter_local_notifications: ^15.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.6.2
  # flutter_stripe: ^9.2.2
  flutter_svg: ^2.0.7
  freezed_annotation: 2.2.0
  go_router: ^9.0.0
  google_sign_in: ^6.1.0
  gql_error_link: ^1.0.0
  gql_http_link: ^1.0.1
  gql_exec: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  i18n_extension: ^9.0.2
  intl: ^0.18.0
  package_info_plus: ^4.0.2
  riverpod_annotation: ^2.1.1
  sentry_flutter: ^7.8.0
  shared_preferences: ^2.1.2
  sign_in_with_apple: ^5.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  ferry_generator: ^0.8.0+1
  freezed: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/

flutter_launcher_icons:
  android: true
  ios: true
