name: aipictors

description: A new Flutter project.

publish_to: "none"

version: 1.1.0+15

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: 3.19.3

dependencies:
  app_tracking_transparency: ^2.0.4
  audioplayers: ^5.2.1
  built_collection: ^5.1.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  dynamic_color: ^1.7.0
  ferry: ^0.15.0+1
  ferry_flutter: ^0.9.0
  ferry_hive_store: ^0.5.2
  firebase_analytics: ^10.8.9
  firebase_app_installations: ^0.2.4+17
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.18
  firebase_dynamic_links: ^5.4.17
  firebase_in_app_messaging: ^0.7.4+17
  firebase_messaging: ^14.7.19
  firebase_remote_config: ^4.3.17
  flame: ^1.16.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_cache_manager: ^3.3.1
  flutter_hooks: ^0.20.5
  flutter_html: 3.0.0-beta.2
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_sign_in: ^6.2.1
  gql_error_link: ^1.0.0+1
  gql_http_link: ^1.0.1+1
  gql_exec: ^1.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  i18n_extension: ^11.0.12
  intl: ^0.18.1
  package_info_plus: ^5.0.1
  riverpod_annotation: ^2.3.5
  sentry_flutter: ^7.18.0
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^6.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  like_button: ^2.0.5
  share_plus: ^7.2.2
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  ferry_generator: ^0.9.1-dev.2
  freezed: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/snd_sine/
    - assets/snd_industrial/
    - assets/snd_piano/

flutter_launcher_icons:
  android: true
  ios: true
