name: aipictors

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  built_collection: ^5.1.1
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  ferry: ^0.14.0+1
  ferry_flutter: ^0.8.0+1
  ferry_hive_store: ^0.5.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.6.2
  go_router: ^6.5.8
  google_sign_in: ^6.1.0
  gql_http_link: ^0.4.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  intl: ^0.18.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  ferry_generator: ^0.8.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
